### ISSUE TITLE
WAS sometimes tries to pop an empty stack during validation.

### ISSUE THREAD

**Issue by leewz** [wasdk/WebAssemblyStudio#246] opened 2018-05-30 23:49 UTC
When I try "Build & Run" for [this project](https://webassembly.studio/?f=bi7eyxp8bt), I get errors in the Javascript console.

Firefox:
> CompileError: wasm validation error: at offset 440: popping value from empty stack

Chrome:
> `Uncaught (in promise) CompileError: AsyncCompile: Compiling wasm function #9:main failed: call found empty stack @+440`

**Comment by leewz** [comment] 2018-05-31 03:42
@yurydelendik This is not an error that showed up within WebAssembly Studio, but an error that went all the way to the browser's Javascript console. The error came from WebAssembly Studio's code.

Within WebAssembly Studio, when Build & Run is pressed, there is no error message or output.

**Comment by yurydelendik** [comment] 2018-05-31 13:08
I still don't understand what is the expected behavior. The description of the issue contains only statement, which looks good to me.

**Comment by leewz** [comment] 2018-05-31 14:06
Within WebAssembly Studio, there is an error caused by the above project
which propagates an exception all the way to the top of the Javascript
layer. It happens in two browsers. The exception shows up in the browser's
Javascript console, not on the page itself.

I don't know enough about WebAssembly Studio to know what the intended
behavior is here.

**Comment by leewz** [comment] 2018-06-02 04:43
Here's an image of what I see after I click "Run".
![wasm studio stack error 440](https://user-images.githubusercontent.com/6633759/40870457-33ae62c4-661f-11e8-8780-9591010981a1.png)

Within the IDE itself, there is no output except a green box. No error message. The error is occurring inside the IDE's code, not my project's code, and nothing catches it. It looks like a bug to me.

**Comment by yurydelendik** [comment] 2018-06-02 12:49
So you are expecting WebAssembly Studio to show this error in IDE. Can you modify issue description and title to reflect it? As stated, the issue is not actionable.

**Comment by leewz** [comment] 2018-06-02 15:35
It should not show the **stack** error in the IDE. It should show the problem in my code that caused the error, or show an error during Build instead of Run, or not show an error at all.

The Build was successful, but the Run caused a Javascript error. This suggests two possible problems:
1. The Build generated invalid WASM.
2. The validation check during Run is wrong.

If my code is wrong, the Build should fail, and say where the problem is. If it is not wrong, the Run should not fail during validation time. It shouldn't be possible for validation to fail from Build.

**Comment by yurydelendik** [comment] 2018-06-05 23:43
Catching errors during Promise execution falls on shoulders of users -- add e.g. `.catch(console.error)` at the end of the chain:

```
...
).then(results => {
  instance = results.instance;
  document.getElementById("container").innerText = instance.exports.main();
}).catch(console.error);
```

Currently there is no way it can be done from a web application. I added similar logging to all examples at 53c5107010882ec06d864f9efdc39d667a1733b3.

Closing as won't fix.

**Closed by yurydelendik** 2018-06-05 23:43 UTC
Labels: question

**Comment by leewz** [comment] 2018-11-01 19:53
For whatever reason, the project now builds and runs without error. I don't believe I made any changes to it, so presumably whatever caused it was fixed.
